export const SHOW_SIDEBAR = 'MAIN-SIDE-BAR/SHOW_SIDEBAR';
export const HIDE_SIDEBAR = 'MAIN-SIDE-BAR/HIDE_SIDEBAR';
export const CHANGE_VIDEO_TO_LOAD = 'FETCH/CHANGE_VIDEO_TO_LOAD';
export const SET_WINDOW_LOCATION = 'APP/CHANGE_WINDOW_LOCATION';
export const SET_ASIDE_BAR_CONFIG = 'APP/SET_ASIDE_BAR_CONFIG';
// export const SET_VIDEO_RATE = 'VIDEO_RATE/SET_VIDEO_RATE';
export const LOG_IN = 'APP/LOG_IN';
export const LOG_OUT = 'APP/LOG_OUT';
