export const SHOW_SIDEBAR = 'MAIN-SIDE-BAR/SHOW_SIDEBAR';
export const HIDE_SIDEBAR = 'MAIN-SIDE-BAR/HIDE_SIDEBAR';
export const CHANGE_VIDEO_TO_LOAD = 'FETCH/CHANGE_VIDEO_TO_LOAD';
export const SET_WINDOW_LOCATION = 'APP/CHANGE_WINDOW_LOCATION';
export const SET_ASIDE_BAR_CONFIG = 'APP/SET_ASIDE_BAR_CONFIG';
